- lxc-images.sh
增加同步`lxc-images`目录下的`streams`目录的相关文件，以支持`LXD/LXC 2.0`。
修改`wget`参数增加`-c -T5`，支持续传与重试(`-c`参数续传，`-T5`代表超时时间5秒，超时则重试)
> make lxc-images support LXD/LXC 2.0

- docker.sh
According to https://docs.docker.com/engine/installation/linux/debian/, packages for debian-stretch are already provided.
> Add debian-stretch repo for docker

- stackage.py
Workaround a bug of stack which doesn't respect case insensitivity of checksums; remove unused clauses in setup info
> Fix bug in stackage.py

- hackage.sh
Hackage had a structural change(from 00-index.tar.gz to 01-index.tar.gz), which the current script does not handle correctly.
I'm not sure if this does all the job.
> Update hackage.sh:Hackage uses 01-index.tar.gz now

- anaconda.py
Since CONDA_CLOUD_REPOS defines channel and arch name, so delete useless arch variable
> anaconda.py: delete useless variable

- nix.py
Add installers for Nix package manager itself.
This script assumes that the mirror ends up being `https://mirrors.tuna.tsinghua.edu.cn/nix`, so using a different URL requires that the ~~`MIRRORED_URL`~~ `MIRROR_BASE_URL` variable be changed accordingly.
> Add Nix package manager

- hackage.sh
根据 https://github.com/tuna/mirror-web/issues/132 ，需要同步一些`json`文件来满足stack package-indices新的安全机制。
尚不清楚增加后是否能完全解决问题，也不太了解同步脚本怎么测试（平时基本不写shell）...抛砖引玉，希望尽快解决
---
These `json` files are required for stack 2.1.1. 
Refs:
* https://docs.haskellstack.org/en/stable/yaml_configuration/#package-indices
* https://hackage.haskell.org/api#security
> hackage新的安全机制需要增加同步若干json文件

- anaconda.py
To add cudatoolkit 9.2 package for Windows
Related issue: https://github.com/tuna/issues/issues/637#event-2746439188
> Add numba with the dev label for the win-64 channel

- dockerfiles/nix-channels/Dockerfile
- nix-channels.py
Having written this:
I have been asked (in personal communication) to move forward with Nix mirroring. So I've decided to slightly polish the script I originally had using a suggestion from @oxalica, and posting it here. Following the final exams I might post details on how I want this to work (or you can infer some from the script).
Some TODOs I can think of:
- Estimated size and rate of growth
- Maybe GC on old store paths
> Add nix-channels (preliminary)

- adoptopenjdk.sh
比如文件`OpenJDK11U-jdk_x86-32_windows_hotspot_11.0.6_10.msi`，现在没有下载。
> 下载AdoptOpenJDK的installer

- dockerfiles/nix-channels/Dockerfile
- nix-channels.py
- nixos-images.py
- Both scripts require the nix-channels docker image
- Run nixos-images **without** old files, nix-channels **with** old files
- nixos-images: Some files just link to a 404, not sure why, I just ignored those files
> nix-channels and nixos-images update due to upstream change

- anaconda.py
New channel for hosting the release candidates of PyTorch: https://anaconda.org/pytorch-test
> Add pytorch rc channel

- dockerfiles/julia/Dockerfile
针对[[镜像请求] Julia：General registry](https://github.com/tuna/issues/issues/837)，用docker封装了一个julia镜像工具 
不是很清楚tunasync-scripts是怎么被调用的，这里大概介绍一下手动执行的方式
build: `docker build dockerfiles/julia julia-mirror`
[[镜像请求] Julia：General registry](https://github.com/tuna/issues/issues/837) 中请求了两类数据的镜像：General registry 以及 Julia binary releases
**假设所有相关的数据存放在 `/julia_mirrors` 文件夹下**，最终得到的文件夹结构大概为：
```text
julia_mirrors/
├── clones # git repo mirrors，每次更新都需要，但是不需要对外提供
├── registries # 存放需要镜像的注册表，每次更新都需要，不需要对外提供
│   └── General
└── static # 所有需要对外提供的资源均在 static 文件夹内
├── artifact # 装包时所需要的二进制依赖
├── package # julia 包的源代码
├── releases # julia 二进制安装程序
│	├── latest
│	├── v1.0
│	├── v1.1
│	├── v1.2
│	├── v1.3
│	└── v1.4
├── registries # 记录当前最新的注册表版本
└── registry # 注册表数据
``` …
> julia mirror

- julia.sh
Cont. 61e6c6b359576a8bfa573482277ac56ee3a6d048
我看了一下[同步状态](https://mirrors.bfsu.edu.cn/status/#syncing-status)好像所有的上游都带有协议前缀，所以这里给 Julia 的上游补上 https 前缀
> add https protocol prefix to julia upstream

- dockerfiles/julia/Dockerfile
- julia.sh
似乎 `julia-releases` 并没有使用 `jill` 作为镜像工具，所以这里移除了 `jill` 的依赖，直接使用官方提供的 `julia:1.4` 镜像
StorageServer `v0.1.0.beta` 的更新：
* bug修复：在更新过程中正常移除一些本应该被移除的临时文件。
* 将预处理(更新 general repo）和后处理过程（`rm /tmp/jl_*`)从`mirror_tarball`里移除了。其中预处理转移到 `julia.sh` 中了，后处理则因为是个临时的docker容器所以不需要了。（算是修复了同步错误的bug: https://github.com/tuna/issues/issues/837#issuecomment-635008614)
另外，这里需要手动清理一次`static`文件夹下的临时文件：
```
find "$PWD/static" -name '*.tmp.*' -delete;
```
cc: @z4yx
> [julia mirror] use StorageServer#v0.1.0.beta and remove jill dependency

- dockerfiles/julia/Dockerfile
- julia.sh
这里的超时策略是：如果某个包（包括所有版本）的拉取过程超过了`PKG_TIMEOUT`，那么就跳过这个包的拉取，继续下一个包。对于增量更新来说，10分钟应该是一个比较宽松的值。
Julia Pkg 在装包时若上游镜像站缺少某一资源，会使用原始地址作为fallback，所以即使增量更新不完整，在大范围内不会太影响整体的使用。
> [julia] skip packages that unexpectedly take a long time

- julia.sh
`https://us-east.storage.julialang.org` 是静态HTTP服务器，是反代形式的`https://pkg.julialang.org`(Pkg Server) 的存储上游。最近PkgServer的改变比较大，可能是导致 https://github.com/tuna/issues/issues/866 的一个原因，但不太确定是否因为如此，仅仅作为一个尝试。
Edit: 我们这边内网服务器连接 `https://us-east.storage.julialang.org` 的网络并不十分好，但我猜 BFSU 应该不会存在这个问题？
> update julia upstream

- dockerfiles/julia/Dockerfile
- julia.sh
address #80
我bash下手动执行是ok的，不过不是特别确定这个在tunasync下是不是能正常跑...
如果需要的话可以改成 https://kr.storage.juliahub.com （韩国首尔）作为上游
> [Julia] upgrade julia mirror script

- dockerfiles/julia/Dockerfile
- dockerfiles/julia/startup.jl
Julia的包共享目前还没有得到很好地支持，需要一些魔改
这里另外添加了一个`startup.jl`文件，不知道路径是不是对了
cc: @z4yx
> [Julia] make /opt/julia a shared julia depot path

- dockerfiles/julia/Dockerfile
现在会直接抛出一个错误，这样的话bash会把它识别为同步失败
```bash
root@storage:~/docker/julia-mirror# julia gen_static.jl 
┌ Warning: ErrorException("type Nothing has no field status")
│   resource = "/registry/23338594-aafe-5451-b93e-139f81909106/65102b89ec1830985bc80d699c1564f6a78a1977"
└ @ StorageMirrorServer ~/.julia/packages/StorageMirrorServer/4Vvsm/src/mirror_tarball.jl:67
┌ Error: failed to fetch registry tarball
│   uuid = "23338594-aafe-5451-b93e-139f81909106"
│   hash = "65102b89ec1830985bc80d699c1564f6a78a1977"
│   upstreams =
│    1-element Array{String,1}:
│     "https://kr.storage.juliahub.com"
└ @ StorageMirrorServer ~/.julia/packages/StorageMirrorServer/4Vvsm/src/mirror_tarball.jl:86
ERROR: LoadError: Stop mirroring.
Stacktrace:
[1] error(::String) at ./error.jl:33
[2] …
```
> [Julia] make registry downloading failure a panic

- dockerfiles/julia/Dockerfile
- dockerfiles/julia/startup.jl
- julia.sh
关于之前失败的版本 (#84) 的更新：
* 完善了异常处理和日志输出
* 多上游情况下，会从第一个返回HEAD请求的上游下载数据
* 最近上游非常不稳定，调大了默认的 timeout 值
Cref: #80
> [julia] upgrade to StorageMirrorServer v0.1.4 and use all official upstreams

- dockerfiles/julia/Dockerfile
- julia.sh
`failed_resources.txt`里面包括的是下载失败的资源：有一些是因为网络原因无法下载，更多的是因为在上游第一次构建的时候源数据URL就已经失效了。单独为这些维护一个 `block_resources.txt` 意义不大，所以设置一个大一点的时间间隔来避免无意义地尝试 `failed_resources.txt`。目前观察下来的下载成功率还蛮高的，所以应该不会有太大问题。
每次增量更新所需的大概时间：
* 尝试 `failed_resources.txt` ：大概20-30分钟
* 不尝试：没有遇到大的artifacts的话，2分钟左右；如果遇到大的artifacts的话就得慢慢耗了
目前观察到的大概是139个无效资源，以及4个下载失败
Cref: #80
> [Julia] skip failed_resources for 5 days until the next try

- dockerfiles/julia/Dockerfile
HTTP.jl is somehow not reliable enough that `HTTP.get` would occasionally hang for unidentified reasons as we've seen all through the initialization of julia mirror. This version uses `curl` instead of `HTTP.get` to fetch resources, which is more stable and faster.
`curl` dependency is included in julia:1.5 base image so we don't need to install it.
> [julia] upgrade to StorageMirrorServer v0.2.0

- github-release.py
Refer to [#999](https://github.com/tuna/issues/issues/999).
There is no license information for `stellarium-data`, hence not included in this PR.
For DSS data, they are too big and infrequently used (maybe) hence not included in this PR.
> Add Stellarium to github-release

- anaconda.py
To install the software MOOSE (Multiphysics Object-Oriented Simulation Environment)
> Add idaholab/linux-64

- nix-channels.py
Assumes that the existence of binary-cache-url indicates that a release
is completely downloaded, because it is the last file written when in
the clone_channels function.
> nix-channels: Check release is complete before GC

- nix-channels.py
if binary-cache-url exists, it means that this repo has been completely downloaded, and should be considered as a candidate of "alive"
See https://github.com/tuna/tunasync-scripts/pull/115#pullrequestreview-578937481-permalink
> nix-channels: fix critical bug in #115

- julia.sh
The current storage server stops providing `/registry/$uuid/$hash` files so the mirror job fails at the start. By switching to pkg servers it should work right now but I'm not sure if it would still work in the future.
See also https://github.com/johnnychen94/StorageMirrorServer.jl/issues/19
> [julia] switch upstreams to pkg servers

- julia.sh
Reverts tuna/tunasync-scripts#117
The issue (https://github.com/johnnychen94/StorageMirrorServer.jl/issues/19) is fixed already in the storage end, so reverting to the normal storage server as it performs better.
> Revert "[julia] switch upstreams to pkg servers"

- apt-sync.py
Defaults to some generic text, customizable from an environment variable `APT_SYNC_USER_AGENT`.
Useful to inform the upstream about your mirror site, which is surely better than just `python-requests/2.23.0`, which may even be banned by popular sites like TUNA.
Implementation method from [this Stack Overflow answer][1].
Extra stuff: I configured my editor to strip trailing whitespaces for Python files.
[1]: https://stackoverflow.com/a/66661349/5958455
> apt-sync.py: Set default User-Agent for requests lib

- elastic.sh
According to https://www.elastic.co/blog/whats-new-elastic-8-0-0 , elastic have released version 8 of elastic stack.
Ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html
> elastic: add 8.x

- adoptium.py
Adoptium's RPM buids update for rhel 7,8, and 9, only update for centos 7. suggest to change centos to rhel. 
https://github.com/taomaree/tunasync-scripts/commit/631e91d01cfdad785bf96a3584f585277189b805
> Adoptium: change centos to rhel for long term support rpm

- yum-sync.py
Since the current CentOS 8 repositories are now under http://mirror.centos.org/centos/8-stream/ we need to be able to download/mirror this repository. When using `8-stream` the script fails as it tries to evaluate stream as an integer making a range from `8` to `stream` which doesn't make sense obviously.
I did this locally and was able to mirror the `8-stream` repos. Just figured someone might also need that :smile:  Let me know if and where to add tests.
> Allow centos 8-stream to be mirrored

- elpa.sh
`gnu` vs `gnu-devel` == `stable-melpa` vs `melpa`
> elpa: Add gnu-devel and nongnu-devel

- apt-sync.py
ros2 has a noble based distro but ros2.sh does not mirror it
See http://packages.ros.org/ros2/ubuntu/dists/noble/
> apt-sync: add noble to @ubuntu-lts

- github-release.py
> 获取releases时添加per_page参数
