tuna/tunasync-scripts

- termux.sh
http://termux.net/dists/stable/main/binary-x86_64/
> termux.sh: Add x86_64 architecture.

- nodesource.sh
nodejs 9 出来一段时间了，希望更新合并这个 pr 更新版本。
https://deb.nodesource.com/node_9.x/
> 更新 node 镜像为 9.x 版本  / update node to 9.x version

- grafana.sh
如何测试？我只是用 curl 确认了 deb repo 的 Release 文件，和 rpm repo 的 repomd.xml 文件
> grafana: upstream repo structure changed

- anaconda.py
> add stackless channels

- anaconda.py
> add intel and auto channel

- anaconda.py
Hello,
This channel includes [deepmd-kit](https://github.com/deepmodeling/deepmd-kit), developed by Beijing Institute of Big Data Research, which is a deep learning package for many-body potential energy representation and molecular dynamics.
The channel is now maintained by me, and I want users in China more easily to install the packages.
Jinzhe
> add deepmodeling to CONDA_CLOUD_REPOS

- anaconda.py
> Add Anaconda cloud source: dglteam

- adoptopenjdk.sh
see https://github.com/tuna/issues/issues/723
> 添加AdoptOpenJDK镜像

- nix-channels.py
- Avoid costly `xz` operation using `nix path-info` and a parallel downloader
- Add garbage collection
Consider squashing
> Update nix channels

- nix.sh
I forgot to do this in #58, sorry
> nix: symlink to latest

- nix-channels.py
Could fix a race that causes FileNotFoundError
> nix-channel: dedup paths before download

- anaconda.py
> add ohmeta channel

- nodesource.sh
closes tuna/issues#871
nodesource镜像更新14.x系列
> add v14.x for nodesource

- anaconda.py
[QIIME 2™](https://qiime2.org)  is a next-generation microbiome bioinformatics platform that is extensible, free, open source, and community developed. So, support [qiime2 channel](https://anaconda.org/qiime2) please.
> add qiime2 channel

- anaconda.py
[Biobakery](https://github.com/biobakery/biobakery) is a bioinformatics analysis toolkit including software, documentation, and tutorials for microbial community profiling. So, support [biobakery channel](https://anaconda.org/biobakery) please.
> add biobakery channel

- github-release.py
See <https://github.com/UNIDY2002/THUInfo> for more info.
Reference: [Learn-Project](https://mirrors.tuna.tsinghua.edu.cn/github-release/xxr3376/Learn-Project/), [LearnX](https://mirrors.tuna.tsinghua.edu.cn/github-release/robertying/learnX/LatestRelease/), [GoAuthing](https://mirrors.tuna.tsinghua.edu.cn/github-release/z4yx/GoAuthing/LatestRelease/)
> Add THUInfo into github-release

- github-release.py
Update repo url of THUInfo since it is changing ownership
> Update repo url of THUInfo

- llvm-apt.sh
Ref to [tuna/issue#1817](https://github.com/tuna/issues/issues/1817)
> llvm-apt: add llvm 17

- nix-channels.py
See https://github.com/tuna/issues/issues/1855
> Workaround for nonexistent paths in store-paths.xz

- mongodb.sh
关于文档,我在本组织内唯一能搜索到的相关文档在这:
https://github.com/tuna/mirrorz-help/blob/d7c616831a93148ea5b714ca61fa7b6d27e56069/contents/mongodb.mdx#L83
但是已经被归档了,不知如何修改
> add mongodb 7.0

- nix-channels.py
- nix-channels: Find nar files in closure separately
- nix-channels: Garbage collect before updating
> nix-channels gc fixes

- github-raw.py
used in https://mirrors.tuna.tsinghua.edu.cn/help/docker-ce/
> feat: add docker/install.sh to github-raw

- cvmfs.sh
> Add cvmfs.sh
